### ISSUE TITLE
On Windows 10, "BertUI has stopped working"

### ISSUE THREAD

**Issue by bjmc** [GeekJosh/BertUI#5]
Immediately after launching, WIndows throws an error "BertUI has stopped working" and closes the program. It seems like it actually *does* work, because the tiles appear, but it's quickly killed by Windows.

Let me know if there's anything I can do to help troubleshoot this issue. I'm not experienced with Windows development.

**Comment by bjmc** [comment]
I found the following details in the windows event viewer:

> Log Name:      Application
Source:        .NET Runtime
Date:          12/04/2016 17:56:46
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-FB2BMEA
Description:
Application: BertUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at <Module>.XInputGetState(UInt32, _XINPUT_STATE*)
   at SlimDX.XInput.Controller.get_IsConnected()
   at BertUI.GamepadState.Update()
   at BertUI.MainWindow.PollGamepad(System.Object, System.Timers.ElapsedEventArgs)

> Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at BertUI.App.Main(System.String[])


> Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-04-12T16:56:46.624870500Z" />
    <EventRecordID>619</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-FB2BMEA</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: BertUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at &lt;Module&gt;.XInputGetState(UInt32, _XINPUT_STATE*)
   at SlimDX.XInput.Controller.get_IsConnected()
   at BertUI.GamepadState.Update()
   at BertUI.MainWindow.PollGamepad(System.Object, System.Timers.ElapsedEventArgs)

> Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at BertUI.App.Main(System.String[])

</Data>
  </EventData>
</Event>

**Comment by rix1337** [comment]
On my fresh Windows 10 install it doesn't even throw an error. The app just does not launch.
On my old HTPC (upgraded from 7) it did work flawlessly...

**Comment by bjmc** [comment]
@GeekJosh Is this app still maintained? It would be great to get it working on Windows 10, because as far as I can tell, there's nothing else quite like it in the Windows world.

Is there anything we can do to help?

**Comment by rix1337** [comment]
I have reached out to @GeekJosh as well... also forked the app  (to remove the shutdown button).
Installing Visual Studio and building the App has allowed me to start the app, but I would not recommend this. VS is an extremely bloated install which forced me to restore my system to fully remove..

Tried installing SlimDX and various .net Redists.. all I know is that fresh Windows 10 does not like this app.

Meanwhile: is there any alternative to BertUI?

**Comment by GeekJosh** [comment]
Hey all, I've not had time to work on BertUI in quite a while, however I am still planning on releasing a new version eventually. It started out as part project to fill a need I had for a simple 10-foot UI, I never really expected anyone else to use it, but the comments/suggestions are very encouraging,thank you.

For this version, I'm going to try to work out what is preventing it launching on Win 10 (it seems to work if you upgraded from 8.1) but that's likely to be the last update for the .NET version as I'm trying to port to Qt, as this should result in a much cleaner, quicker to launch program. Problem is, I'm learning C++ as I go so progress is a little slow. Hopefully I'll get this done before it loses relevance, thanks for your bug reports they do help.

**Comment by rix1337** [comment]
Thank you for the Update.

Meanwhile I've hacked together a VB.net rebuild of BertUI if any of you are interested:
https://github.com/rix1337/HTPC-UI/releases/tag/v.1.0.0.0

Its no beauty (no settings file, etc.) but can be quickly adapted in Visual Studio 2010 Express and works..
